# Data Analytics III

1. Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv
dataset.
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision,
Recall on the given dataset.

In [2]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Import Dataset
iris = pd.read_csv("IRIS.csv")

In [4]:
# Display DataFrame
iris

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [7]:
# Check Unique Features
iris["species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [11]:
# Check value count for each Category
iris["species"].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: species, dtype: int64

In [12]:
# Check for missing values
iris.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [13]:
# Create Data
X = iris.drop("species", axis=1)
y = iris["species"]

In [15]:
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [16]:
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: species, dtype: object

In [27]:
# Encode the y data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [29]:
# Transform into dataframe
y = pd.DataFrame(y, columns=["species"])
y.head()

species
0        0
1        0
2        0
3        0
4        0

In [113]:
# Split the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [114]:
X_train.head()

sepal_length  sepal_width  petal_length  petal_width
148           6.2          3.4           5.4          2.3
105           7.6          3.0           6.6          2.1
62            6.0          2.2           4.0          1.0
89            5.5          2.5           4.0          1.3
20            5.4          3.4           1.7          0.2

In [115]:
X_test.head()

sepal_length  sepal_width  petal_length  petal_width
46            5.1          3.8           1.6          0.2
110           6.5          3.2           5.1          2.0
38            4.4          3.0           1.3          0.2
117           7.7          3.8           6.7          2.2
29            4.7          3.2           1.6          0.2

In [116]:
y_train.head()

species
148        2
105        2
62         1
89         1
20         0

In [117]:
y_test.head()

species
46         0
110        2
38         0
117        2
29         0

In [118]:
# Scaling X_train and X_test DataFrame
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [119]:
X_train_scaled

array([[ 0.37309043,  0.78193641,  0.90233099,  1.44954572],
       [ 2.13870145, -0.13798878,  1.59680272,  1.17881344],
       [ 0.12086028, -1.97783914,  0.09211396, -0.31021406],
       [-0.50971509, -1.28789526,  0.09211396,  0.09588435],
       [-0.63583016,  0.78193641, -1.23895687, -1.39314316],
       [-1.14029046,  0.55195511, -1.4125748 , -1.39314316],
       [ 2.51704667,  1.70186159,  1.48105743,  1.04344731],
       [-0.38360001, -0.82793266,  0.20785925,  0.09588435],
       [-1.3925206 , -0.13798878, -1.4125748 , -1.5285093 ],
       [ 0.4992055 , -1.74785785,  0.32360454,  0.09588435],
       [ 1.00366579,  0.09199252,  0.32360454,  0.23125048],
       [ 2.26481653, -0.13798878,  1.3074395 ,  1.44954572],
       [-0.63583016,  0.78193641, -1.35470216, -1.12241089],
       [-1.14029046, -0.13798878, -1.29682951, -1.39314316],
       [ 0.24697535, -1.05791396,  1.01807628,  0.23125048],
       [ 1.12978087,  0.32197381,  1.19169421,  1.44954572],
       [-0.63583016,  1.

In [120]:
X_test_scaled

array([[-1.01417538,  1.70186159, -1.29682951, -1.39314316],
       [ 0.75143565,  0.32197381,  0.72871305,  1.04344731],
       [-1.8969809 , -0.13798878, -1.47044745, -1.39314316],
       [ 2.26481653,  1.70186159,  1.65467537,  1.31417958],
       [-1.51863568,  0.32197381, -1.29682951, -1.39314316],
       [-0.13136987, -0.82793266,  0.72871305,  0.90808117],
       [ 1.63424116,  1.241899  ,  1.3074395 ,  1.72027799],
       [ 0.12086028, -1.97783914,  0.67084041,  0.36661662],
       [-0.13136987, -1.05791396,  0.09211396, -0.03948179],
       [-1.26640553,  0.09199252, -1.35470216, -1.5285093 ],
       [-1.26640553, -0.13798878, -1.4125748 , -1.39314316],
       [-1.8969809 , -0.36797007, -1.4125748 , -1.39314316],
       [-1.64475075,  0.09199252, -1.35470216, -1.39314316],
       [ 0.37309043, -1.97783914,  0.38147718,  0.36661662],
       [-1.14029046, -1.74785785, -0.31299455, -0.31021406],
       [-0.88806031,  0.78193641, -1.4125748 , -1.39314316],
       [-1.26640553,  0.

In [121]:
# Convert to DataFrame
X_train_scaled = pd.DataFrame(X_train_scaled, columns=["sepal_length", "sepal_width", "petal_length", "petal_width"])
X_train_scaled.head()

sepal_length  sepal_width  petal_length  petal_width
0      0.373090     0.781936      0.902331     1.449546
1      2.138701    -0.137989      1.596803     1.178813
2      0.120860    -1.977839      0.092114    -0.310214
3     -0.509715    -1.287895      0.092114     0.095884
4     -0.635830     0.781936     -1.238957    -1.393143

In [122]:
X_test_scaled = pd.DataFrame(X_test_scaled, columns=["sepal_length", "sepal_width", "petal_length", "petal_width"])
X_test_scaled.head()

sepal_length  sepal_width  petal_length  petal_width
0     -1.014175     1.701862     -1.296830    -1.393143
1      0.751436     0.321974      0.728713     1.043447
2     -1.896981    -0.137989     -1.470447    -1.393143
3      2.264817     1.701862      1.654675     1.314180
4     -1.518636     0.321974     -1.296830    -1.393143

In [123]:
# Fit the Model
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()

clf.fit(X_train_scaled, y_train.values.ravel())

GaussianNB()

In [124]:
y_pred = clf.predict(X_test_scaled)

In [125]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[13,  0,  0],
       [ 0,  8,  0],
       [ 0,  2,  7]])

In [126]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred, average=None, zero_division=1)
# precision = precision_score(y_test, y_train, average='micro', zero_division=1)
f1 = f1_score(y_test, y_pred, average='micro')
print("Accuracy: ", accuracy)
print("Error Rate: ", (1-accuracy))
print("Reacll: ", recall)
# print("Precision: ", precision)
print("F1: ", f1)

Accuracy:  0.9333333333333333
Error Rate:  0.06666666666666665
Reacll:  [1.         1.         0.77777778]
F1:  0.9333333333333333
